name: Instrumentation-Test

on:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]') && ! (contains(toJSON(github.event.commits.*.message), '[skip ') && contains(toJSON(github.event.commits.*.message), '#coverage'))"
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    strategy:
      matrix:
        api-level: [29]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew test

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          disable-animations: true
          script: ./gradlew connectedCheck